name: Build and Upload Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, arm]
        compiler: [gcc, clang]
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - uses: jirutka/setup-alpine@v1
      - name: Prepare build environment
        run: ./.ci-prepare.sh ${{ matrix.compiler }}
        shell: alpine.sh --root {0}
      - name: Build
        run: ./.ci-build.sh
        shell: alpine.sh {0}
      - name: Find Kernel Files
        id: find-kernel
        run: |
          find .. -name "*.deb" -type f
        shell: bash

      - name: Upload Kernel
        uses: actions/upload-artifact@v2
        with:
          name: Kernel
          path: ${{ steps.find-kernel.outputs.stdout }}
